// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gemm.proto

package com.zmqsample;

public final class Gemm {
  private Gemm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MatrixOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zmqsample.Matrix)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 dimensionX = 1;</code>
     */
    boolean hasDimensionX();
    /**
     * <code>required int32 dimensionX = 1;</code>
     */
    int getDimensionX();

    /**
     * <code>required int32 dimensionY = 2;</code>
     */
    boolean hasDimensionY();
    /**
     * <code>required int32 dimensionY = 2;</code>
     */
    int getDimensionY();

    /**
     * <code>repeated float element = 3;</code>
     */
    java.util.List<java.lang.Float> getElementList();
    /**
     * <code>repeated float element = 3;</code>
     */
    int getElementCount();
    /**
     * <code>repeated float element = 3;</code>
     */
    float getElement(int index);
  }
  /**
   * Protobuf type {@code com.zmqsample.Matrix}
   */
  public  static final class Matrix extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zmqsample.Matrix)
      MatrixOrBuilder {
    // Use Matrix.newBuilder() to construct.
    private Matrix(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Matrix() {
      dimensionX_ = 0;
      dimensionY_ = 0;
      element_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Matrix(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              dimensionX_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              dimensionY_ = input.readInt32();
              break;
            }
            case 29: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                element_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000004;
              }
              element_.add(input.readFloat());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                element_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                element_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          element_ = java.util.Collections.unmodifiableList(element_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zmqsample.Gemm.internal_static_com_zmqsample_Matrix_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zmqsample.Gemm.internal_static_com_zmqsample_Matrix_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zmqsample.Gemm.Matrix.class, com.zmqsample.Gemm.Matrix.Builder.class);
    }

    private int bitField0_;
    public static final int DIMENSIONX_FIELD_NUMBER = 1;
    private int dimensionX_;
    /**
     * <code>required int32 dimensionX = 1;</code>
     */
    public boolean hasDimensionX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 dimensionX = 1;</code>
     */
    public int getDimensionX() {
      return dimensionX_;
    }

    public static final int DIMENSIONY_FIELD_NUMBER = 2;
    private int dimensionY_;
    /**
     * <code>required int32 dimensionY = 2;</code>
     */
    public boolean hasDimensionY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 dimensionY = 2;</code>
     */
    public int getDimensionY() {
      return dimensionY_;
    }

    public static final int ELEMENT_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Float> element_;
    /**
     * <code>repeated float element = 3;</code>
     */
    public java.util.List<java.lang.Float>
        getElementList() {
      return element_;
    }
    /**
     * <code>repeated float element = 3;</code>
     */
    public int getElementCount() {
      return element_.size();
    }
    /**
     * <code>repeated float element = 3;</code>
     */
    public float getElement(int index) {
      return element_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDimensionX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDimensionY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, dimensionX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, dimensionY_);
      }
      for (int i = 0; i < element_.size(); i++) {
        output.writeFloat(3, element_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, dimensionX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dimensionY_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getElementList().size();
        size += dataSize;
        size += 1 * getElementList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zmqsample.Gemm.Matrix)) {
        return super.equals(obj);
      }
      com.zmqsample.Gemm.Matrix other = (com.zmqsample.Gemm.Matrix) obj;

      boolean result = true;
      result = result && (hasDimensionX() == other.hasDimensionX());
      if (hasDimensionX()) {
        result = result && (getDimensionX()
            == other.getDimensionX());
      }
      result = result && (hasDimensionY() == other.hasDimensionY());
      if (hasDimensionY()) {
        result = result && (getDimensionY()
            == other.getDimensionY());
      }
      result = result && getElementList()
          .equals(other.getElementList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDimensionX()) {
        hash = (37 * hash) + DIMENSIONX_FIELD_NUMBER;
        hash = (53 * hash) + getDimensionX();
      }
      if (hasDimensionY()) {
        hash = (37 * hash) + DIMENSIONY_FIELD_NUMBER;
        hash = (53 * hash) + getDimensionY();
      }
      if (getElementCount() > 0) {
        hash = (37 * hash) + ELEMENT_FIELD_NUMBER;
        hash = (53 * hash) + getElementList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zmqsample.Gemm.Matrix parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zmqsample.Gemm.Matrix parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zmqsample.Gemm.Matrix parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zmqsample.Gemm.Matrix parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zmqsample.Gemm.Matrix parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zmqsample.Gemm.Matrix parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zmqsample.Gemm.Matrix parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zmqsample.Gemm.Matrix parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zmqsample.Gemm.Matrix parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zmqsample.Gemm.Matrix parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zmqsample.Gemm.Matrix prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zmqsample.Matrix}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zmqsample.Matrix)
        com.zmqsample.Gemm.MatrixOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zmqsample.Gemm.internal_static_com_zmqsample_Matrix_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zmqsample.Gemm.internal_static_com_zmqsample_Matrix_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zmqsample.Gemm.Matrix.class, com.zmqsample.Gemm.Matrix.Builder.class);
      }

      // Construct using com.zmqsample.Gemm.Matrix.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        dimensionX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        dimensionY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        element_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zmqsample.Gemm.internal_static_com_zmqsample_Matrix_descriptor;
      }

      public com.zmqsample.Gemm.Matrix getDefaultInstanceForType() {
        return com.zmqsample.Gemm.Matrix.getDefaultInstance();
      }

      public com.zmqsample.Gemm.Matrix build() {
        com.zmqsample.Gemm.Matrix result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zmqsample.Gemm.Matrix buildPartial() {
        com.zmqsample.Gemm.Matrix result = new com.zmqsample.Gemm.Matrix(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dimensionX_ = dimensionX_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dimensionY_ = dimensionY_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          element_ = java.util.Collections.unmodifiableList(element_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.element_ = element_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zmqsample.Gemm.Matrix) {
          return mergeFrom((com.zmqsample.Gemm.Matrix)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zmqsample.Gemm.Matrix other) {
        if (other == com.zmqsample.Gemm.Matrix.getDefaultInstance()) return this;
        if (other.hasDimensionX()) {
          setDimensionX(other.getDimensionX());
        }
        if (other.hasDimensionY()) {
          setDimensionY(other.getDimensionY());
        }
        if (!other.element_.isEmpty()) {
          if (element_.isEmpty()) {
            element_ = other.element_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureElementIsMutable();
            element_.addAll(other.element_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDimensionX()) {
          return false;
        }
        if (!hasDimensionY()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zmqsample.Gemm.Matrix parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zmqsample.Gemm.Matrix) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int dimensionX_ ;
      /**
       * <code>required int32 dimensionX = 1;</code>
       */
      public boolean hasDimensionX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 dimensionX = 1;</code>
       */
      public int getDimensionX() {
        return dimensionX_;
      }
      /**
       * <code>required int32 dimensionX = 1;</code>
       */
      public Builder setDimensionX(int value) {
        bitField0_ |= 0x00000001;
        dimensionX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 dimensionX = 1;</code>
       */
      public Builder clearDimensionX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dimensionX_ = 0;
        onChanged();
        return this;
      }

      private int dimensionY_ ;
      /**
       * <code>required int32 dimensionY = 2;</code>
       */
      public boolean hasDimensionY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 dimensionY = 2;</code>
       */
      public int getDimensionY() {
        return dimensionY_;
      }
      /**
       * <code>required int32 dimensionY = 2;</code>
       */
      public Builder setDimensionY(int value) {
        bitField0_ |= 0x00000002;
        dimensionY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 dimensionY = 2;</code>
       */
      public Builder clearDimensionY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dimensionY_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Float> element_ = java.util.Collections.emptyList();
      private void ensureElementIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          element_ = new java.util.ArrayList<java.lang.Float>(element_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public java.util.List<java.lang.Float>
          getElementList() {
        return java.util.Collections.unmodifiableList(element_);
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public int getElementCount() {
        return element_.size();
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public float getElement(int index) {
        return element_.get(index);
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public Builder setElement(
          int index, float value) {
        ensureElementIsMutable();
        element_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public Builder addElement(float value) {
        ensureElementIsMutable();
        element_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public Builder addAllElement(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureElementIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, element_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float element = 3;</code>
       */
      public Builder clearElement() {
        element_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zmqsample.Matrix)
    }

    // @@protoc_insertion_point(class_scope:com.zmqsample.Matrix)
    private static final com.zmqsample.Gemm.Matrix DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zmqsample.Gemm.Matrix();
    }

    public static com.zmqsample.Gemm.Matrix getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Matrix>
        PARSER = new com.google.protobuf.AbstractParser<Matrix>() {
      public Matrix parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Matrix(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Matrix> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Matrix> getParserForType() {
      return PARSER;
    }

    public com.zmqsample.Gemm.Matrix getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MatrixGemmOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zmqsample.MatrixGemm)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
     */
    boolean hasMatrixA();
    /**
     * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
     */
    com.zmqsample.Gemm.Matrix getMatrixA();
    /**
     * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
     */
    com.zmqsample.Gemm.MatrixOrBuilder getMatrixAOrBuilder();

    /**
     * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
     */
    boolean hasMatrixB();
    /**
     * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
     */
    com.zmqsample.Gemm.Matrix getMatrixB();
    /**
     * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
     */
    com.zmqsample.Gemm.MatrixOrBuilder getMatrixBOrBuilder();
  }
  /**
   * Protobuf type {@code com.zmqsample.MatrixGemm}
   */
  public  static final class MatrixGemm extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zmqsample.MatrixGemm)
      MatrixGemmOrBuilder {
    // Use MatrixGemm.newBuilder() to construct.
    private MatrixGemm(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MatrixGemm() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MatrixGemm(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.zmqsample.Gemm.Matrix.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = matrixA_.toBuilder();
              }
              matrixA_ = input.readMessage(com.zmqsample.Gemm.Matrix.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(matrixA_);
                matrixA_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.zmqsample.Gemm.Matrix.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = matrixB_.toBuilder();
              }
              matrixB_ = input.readMessage(com.zmqsample.Gemm.Matrix.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(matrixB_);
                matrixB_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zmqsample.Gemm.internal_static_com_zmqsample_MatrixGemm_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zmqsample.Gemm.internal_static_com_zmqsample_MatrixGemm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zmqsample.Gemm.MatrixGemm.class, com.zmqsample.Gemm.MatrixGemm.Builder.class);
    }

    private int bitField0_;
    public static final int MATRIXA_FIELD_NUMBER = 1;
    private com.zmqsample.Gemm.Matrix matrixA_;
    /**
     * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
     */
    public boolean hasMatrixA() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
     */
    public com.zmqsample.Gemm.Matrix getMatrixA() {
      return matrixA_ == null ? com.zmqsample.Gemm.Matrix.getDefaultInstance() : matrixA_;
    }
    /**
     * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
     */
    public com.zmqsample.Gemm.MatrixOrBuilder getMatrixAOrBuilder() {
      return matrixA_ == null ? com.zmqsample.Gemm.Matrix.getDefaultInstance() : matrixA_;
    }

    public static final int MATRIXB_FIELD_NUMBER = 2;
    private com.zmqsample.Gemm.Matrix matrixB_;
    /**
     * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
     */
    public boolean hasMatrixB() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
     */
    public com.zmqsample.Gemm.Matrix getMatrixB() {
      return matrixB_ == null ? com.zmqsample.Gemm.Matrix.getDefaultInstance() : matrixB_;
    }
    /**
     * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
     */
    public com.zmqsample.Gemm.MatrixOrBuilder getMatrixBOrBuilder() {
      return matrixB_ == null ? com.zmqsample.Gemm.Matrix.getDefaultInstance() : matrixB_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMatrixA()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMatrixB()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMatrixA().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMatrixB().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getMatrixA());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getMatrixB());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMatrixA());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMatrixB());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zmqsample.Gemm.MatrixGemm)) {
        return super.equals(obj);
      }
      com.zmqsample.Gemm.MatrixGemm other = (com.zmqsample.Gemm.MatrixGemm) obj;

      boolean result = true;
      result = result && (hasMatrixA() == other.hasMatrixA());
      if (hasMatrixA()) {
        result = result && getMatrixA()
            .equals(other.getMatrixA());
      }
      result = result && (hasMatrixB() == other.hasMatrixB());
      if (hasMatrixB()) {
        result = result && getMatrixB()
            .equals(other.getMatrixB());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMatrixA()) {
        hash = (37 * hash) + MATRIXA_FIELD_NUMBER;
        hash = (53 * hash) + getMatrixA().hashCode();
      }
      if (hasMatrixB()) {
        hash = (37 * hash) + MATRIXB_FIELD_NUMBER;
        hash = (53 * hash) + getMatrixB().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zmqsample.Gemm.MatrixGemm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zmqsample.Gemm.MatrixGemm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zmqsample.Gemm.MatrixGemm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zmqsample.Gemm.MatrixGemm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zmqsample.Gemm.MatrixGemm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zmqsample.Gemm.MatrixGemm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zmqsample.Gemm.MatrixGemm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zmqsample.Gemm.MatrixGemm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zmqsample.Gemm.MatrixGemm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zmqsample.Gemm.MatrixGemm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zmqsample.Gemm.MatrixGemm prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zmqsample.MatrixGemm}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zmqsample.MatrixGemm)
        com.zmqsample.Gemm.MatrixGemmOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zmqsample.Gemm.internal_static_com_zmqsample_MatrixGemm_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zmqsample.Gemm.internal_static_com_zmqsample_MatrixGemm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zmqsample.Gemm.MatrixGemm.class, com.zmqsample.Gemm.MatrixGemm.Builder.class);
      }

      // Construct using com.zmqsample.Gemm.MatrixGemm.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMatrixAFieldBuilder();
          getMatrixBFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (matrixABuilder_ == null) {
          matrixA_ = null;
        } else {
          matrixABuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (matrixBBuilder_ == null) {
          matrixB_ = null;
        } else {
          matrixBBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zmqsample.Gemm.internal_static_com_zmqsample_MatrixGemm_descriptor;
      }

      public com.zmqsample.Gemm.MatrixGemm getDefaultInstanceForType() {
        return com.zmqsample.Gemm.MatrixGemm.getDefaultInstance();
      }

      public com.zmqsample.Gemm.MatrixGemm build() {
        com.zmqsample.Gemm.MatrixGemm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zmqsample.Gemm.MatrixGemm buildPartial() {
        com.zmqsample.Gemm.MatrixGemm result = new com.zmqsample.Gemm.MatrixGemm(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (matrixABuilder_ == null) {
          result.matrixA_ = matrixA_;
        } else {
          result.matrixA_ = matrixABuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (matrixBBuilder_ == null) {
          result.matrixB_ = matrixB_;
        } else {
          result.matrixB_ = matrixBBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zmqsample.Gemm.MatrixGemm) {
          return mergeFrom((com.zmqsample.Gemm.MatrixGemm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zmqsample.Gemm.MatrixGemm other) {
        if (other == com.zmqsample.Gemm.MatrixGemm.getDefaultInstance()) return this;
        if (other.hasMatrixA()) {
          mergeMatrixA(other.getMatrixA());
        }
        if (other.hasMatrixB()) {
          mergeMatrixB(other.getMatrixB());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMatrixA()) {
          return false;
        }
        if (!hasMatrixB()) {
          return false;
        }
        if (!getMatrixA().isInitialized()) {
          return false;
        }
        if (!getMatrixB().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zmqsample.Gemm.MatrixGemm parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zmqsample.Gemm.MatrixGemm) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.zmqsample.Gemm.Matrix matrixA_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zmqsample.Gemm.Matrix, com.zmqsample.Gemm.Matrix.Builder, com.zmqsample.Gemm.MatrixOrBuilder> matrixABuilder_;
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public boolean hasMatrixA() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public com.zmqsample.Gemm.Matrix getMatrixA() {
        if (matrixABuilder_ == null) {
          return matrixA_ == null ? com.zmqsample.Gemm.Matrix.getDefaultInstance() : matrixA_;
        } else {
          return matrixABuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public Builder setMatrixA(com.zmqsample.Gemm.Matrix value) {
        if (matrixABuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          matrixA_ = value;
          onChanged();
        } else {
          matrixABuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public Builder setMatrixA(
          com.zmqsample.Gemm.Matrix.Builder builderForValue) {
        if (matrixABuilder_ == null) {
          matrixA_ = builderForValue.build();
          onChanged();
        } else {
          matrixABuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public Builder mergeMatrixA(com.zmqsample.Gemm.Matrix value) {
        if (matrixABuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              matrixA_ != null &&
              matrixA_ != com.zmqsample.Gemm.Matrix.getDefaultInstance()) {
            matrixA_ =
              com.zmqsample.Gemm.Matrix.newBuilder(matrixA_).mergeFrom(value).buildPartial();
          } else {
            matrixA_ = value;
          }
          onChanged();
        } else {
          matrixABuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public Builder clearMatrixA() {
        if (matrixABuilder_ == null) {
          matrixA_ = null;
          onChanged();
        } else {
          matrixABuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public com.zmqsample.Gemm.Matrix.Builder getMatrixABuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMatrixAFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      public com.zmqsample.Gemm.MatrixOrBuilder getMatrixAOrBuilder() {
        if (matrixABuilder_ != null) {
          return matrixABuilder_.getMessageOrBuilder();
        } else {
          return matrixA_ == null ?
              com.zmqsample.Gemm.Matrix.getDefaultInstance() : matrixA_;
        }
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixA = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zmqsample.Gemm.Matrix, com.zmqsample.Gemm.Matrix.Builder, com.zmqsample.Gemm.MatrixOrBuilder> 
          getMatrixAFieldBuilder() {
        if (matrixABuilder_ == null) {
          matrixABuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zmqsample.Gemm.Matrix, com.zmqsample.Gemm.Matrix.Builder, com.zmqsample.Gemm.MatrixOrBuilder>(
                  getMatrixA(),
                  getParentForChildren(),
                  isClean());
          matrixA_ = null;
        }
        return matrixABuilder_;
      }

      private com.zmqsample.Gemm.Matrix matrixB_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zmqsample.Gemm.Matrix, com.zmqsample.Gemm.Matrix.Builder, com.zmqsample.Gemm.MatrixOrBuilder> matrixBBuilder_;
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public boolean hasMatrixB() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public com.zmqsample.Gemm.Matrix getMatrixB() {
        if (matrixBBuilder_ == null) {
          return matrixB_ == null ? com.zmqsample.Gemm.Matrix.getDefaultInstance() : matrixB_;
        } else {
          return matrixBBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public Builder setMatrixB(com.zmqsample.Gemm.Matrix value) {
        if (matrixBBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          matrixB_ = value;
          onChanged();
        } else {
          matrixBBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public Builder setMatrixB(
          com.zmqsample.Gemm.Matrix.Builder builderForValue) {
        if (matrixBBuilder_ == null) {
          matrixB_ = builderForValue.build();
          onChanged();
        } else {
          matrixBBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public Builder mergeMatrixB(com.zmqsample.Gemm.Matrix value) {
        if (matrixBBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              matrixB_ != null &&
              matrixB_ != com.zmqsample.Gemm.Matrix.getDefaultInstance()) {
            matrixB_ =
              com.zmqsample.Gemm.Matrix.newBuilder(matrixB_).mergeFrom(value).buildPartial();
          } else {
            matrixB_ = value;
          }
          onChanged();
        } else {
          matrixBBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public Builder clearMatrixB() {
        if (matrixBBuilder_ == null) {
          matrixB_ = null;
          onChanged();
        } else {
          matrixBBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public com.zmqsample.Gemm.Matrix.Builder getMatrixBBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMatrixBFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      public com.zmqsample.Gemm.MatrixOrBuilder getMatrixBOrBuilder() {
        if (matrixBBuilder_ != null) {
          return matrixBBuilder_.getMessageOrBuilder();
        } else {
          return matrixB_ == null ?
              com.zmqsample.Gemm.Matrix.getDefaultInstance() : matrixB_;
        }
      }
      /**
       * <code>required .com.zmqsample.Matrix matrixB = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zmqsample.Gemm.Matrix, com.zmqsample.Gemm.Matrix.Builder, com.zmqsample.Gemm.MatrixOrBuilder> 
          getMatrixBFieldBuilder() {
        if (matrixBBuilder_ == null) {
          matrixBBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zmqsample.Gemm.Matrix, com.zmqsample.Gemm.Matrix.Builder, com.zmqsample.Gemm.MatrixOrBuilder>(
                  getMatrixB(),
                  getParentForChildren(),
                  isClean());
          matrixB_ = null;
        }
        return matrixBBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zmqsample.MatrixGemm)
    }

    // @@protoc_insertion_point(class_scope:com.zmqsample.MatrixGemm)
    private static final com.zmqsample.Gemm.MatrixGemm DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zmqsample.Gemm.MatrixGemm();
    }

    public static com.zmqsample.Gemm.MatrixGemm getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MatrixGemm>
        PARSER = new com.google.protobuf.AbstractParser<MatrixGemm>() {
      public MatrixGemm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MatrixGemm(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MatrixGemm> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MatrixGemm> getParserForType() {
      return PARSER;
    }

    public com.zmqsample.Gemm.MatrixGemm getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zmqsample_Matrix_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zmqsample_Matrix_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zmqsample_MatrixGemm_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zmqsample_MatrixGemm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nGemm.proto\022\rcom.zmqsample\"A\n\006Matrix\022\022\n" +
      "\ndimensionX\030\001 \002(\005\022\022\n\ndimensionY\030\002 \002(\005\022\017\n" +
      "\007element\030\003 \003(\002\"\\\n\nMatrixGemm\022&\n\007matrixA\030" +
      "\001 \002(\0132\025.com.zmqsample.Matrix\022&\n\007matrixB\030" +
      "\002 \002(\0132\025.com.zmqsample.MatrixB\025\n\rcom.zmqs" +
      "ampleB\004Gemm"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zmqsample_Matrix_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zmqsample_Matrix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zmqsample_Matrix_descriptor,
        new java.lang.String[] { "DimensionX", "DimensionY", "Element", });
    internal_static_com_zmqsample_MatrixGemm_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zmqsample_MatrixGemm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zmqsample_MatrixGemm_descriptor,
        new java.lang.String[] { "MatrixA", "MatrixB", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
